name: obfuscate + deploy to github pages
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install obfuscation tools
        run: |
          npm i -g javascript-obfuscator html-minifier-terser clean-css-cli

      - name: obfuscate js
        run: |
          find . -maxdepth 1 -name "*.js" | while read -r f; do
            echo "obfuscating $f"
            tmp="${f}.tmp"
            javascript-obfuscator "$f" \
              --output "$tmp" \
              --compact true \
              --control-flow-flattening true \
              --string-array true \
              --string-array-threshold 0.75 \
              --rotate-string-array true \
              --disable-console-output true
            mv "$tmp" "$f"
          done

      - name: minify css
        run: |
          find . -maxdepth 1 -name "*.css" | while read -r f; do
            echo "minifying $f"
            cleancss -o "$f" "$f" || true
          done

      - name: minify html
        run: |
          find . -maxdepth 1 -name "*.html" | while read -r f; do
            echo "minifying $f"
            html-minifier-terser "$f" \
              --collapse-whitespace \
              --remove-comments \
              --minify-js \
              --minify-css \
              -o "$f" || true
          done

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
