name: obfuscate + deploy to github pages
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install obfuscation tools
        run: |
          npm i -g javascript-obfuscator@4 html-minifier-terser clean-css-cli

      - name: obfuscate all .js files (recursively)
        run: |
          set -e
          # find all JS files (recursively) and obfuscate them in-place
          find . -type f -name "*.js" ! -path "./node_modules/*" | while read -r f; do
            echo "obfuscating $f"
            tmp="${f}.obftmp"
            # CLI-safe flags only (avoid JS-API-only flags like --rotate-string-array)
            javascript-obfuscator "$f" \
              --output "$tmp" \
              --compact true \
              --control-flow-flattening true \
              --control-flow-flattening-threshold 0.75 \
              --numbers-to-expressions true \
              --string-array true \
              --string-array-threshold 0.75 \
              --disable-console-output true \
              --self-defending false
            # replace original
            mv "$tmp" "$f"
          done

      - name: minify css (recursively)
        run: |
          find . -type f -name "*.css" ! -path "./node_modules/*" | while read -r f; do
            echo "minifying $f"
            cleancss -o "$f" "$f" || true
          done

      - name: minify html (recursively)
        run: |
          find . -type f -name "*.html" ! -path "./node_modules/*" | while read -r f; do
            echo "minifying $f"
            html-minifier-terser "$f" \
              --collapse-whitespace \
              --remove-comments \
              --remove-redundant-attributes \
              --remove-empty-attributes \
              --minify-js \
              --minify-css \
              -o "$f" || true
          done

      - name: remove sourcemaps
        run: |
          find . -type f -name "*.map" -print -delete || true

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
